# docker-compose.yml
version: '3'
services:
  database:
    ports:
      - "5432:5432"
    image: "postgres" # use latest official postgres version
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=midnite
    volumes:
      - database-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  database-data:  # named volumes can be managed easier using docker-compose


